/**
 * Source-derived question bank: every record of docs/sources/apohenia/Impact_Question_Bank.md
 * as data. Generated from the markdown by a one-off parser and checked in; the template and
 * purpose text is the bank's editorially normalized wording, not a verbatim transcript quote.
 *
 * Use classes (from the bank's own header):
 * - adapt: a question objective that may be adapted into an approved live track.
 * - study_only: preserved for study, never entered into a live prompt or hint.
 * - private_training: self-directed practice and reflection for the rep, never prospect-facing.
 *
 * The raw source excerpts are deliberately not included here. They live in the source file.
 * Pure data: no React, no fetch, no clock.
 */

export type QuestionUse = "adapt" | "study_only" | "private_training";

export type QuestionPhase =
  | "intent"
  | "logicalCertainty"
  | "setterTransition"
  | "emotionalCertainty"
  | "pitch"
  | "mirror"
  | "objection"
  | "identityAndTaxonomy"
  | "training"
  | "followUp"
  | "referral"
  | "upsellSetting"
  | "upsellClosing"
  | "reviewedCall";

export interface QuestionRecord {
  /** Bank id, e.g. "L06". The letter is the bank's own series; the phase is derived from it. */
  id: string;
  phase: QuestionPhase;
  label: string;
  /** Editorially normalized template. Bracketed parts are slots the seller fills from the conversation. */
  template: string;
  /** The instructor's intended purpose, as the bank states it. */
  purpose: string;
  /** Delivery described in the source text. Described, not measured from audio. */
  delivery: string;
  use: QuestionUse;
  /** Source file, section and original character range, as the bank cites it. */
  sourceRef: string;
}

export const QUESTION_BANK: readonly QuestionRecord[] = [
  { id: "I01", phase: "intent", label: "contact identity", template: "Is this [name]?", purpose: "Confirm the intended person.", delivery: "casual", use: "adapt", sourceRef: "A, A01, original characters [7620, 8197)" },
  { id: "I02", phase: "intent", label: "lead action confirmed", template: "It looks like you [documented action] about [desired result]. Is that right?", purpose: "Reconnect the call to the action that created the lead.", delivery: "casual-curious", use: "adapt", sourceRef: "A, A01, original characters [7859, 8446)" },
  { id: "I03", phase: "intent", label: "tangible", template: "What was your intent behind [action]? What were you hoping to get out of it?", purpose: "Elicit the tangible: a desired future outcome.", delivery: "curious", use: "adapt", sourceRef: "A, A01, original characters [8128, 8725)" },
  { id: "I04", phase: "intent", label: "experience", template: "What have you seen that makes you feel you are not [achieving desired result]?", purpose: "Elicit the past/present experience behind the tangible.", delivery: "curious", use: "adapt", sourceRef: "A, A01, original characters [9129, 9735)" },
  { id: "I05", phase: "intent", label: "connection ok", template: "Can you hear me? Can you see me?", purpose: "Check the video-call connection; see-me only on video.", delivery: "casual", use: "adapt", sourceRef: "A, A04, original characters [26381, 26955)" },
  { id: "I06", phase: "intent", label: "specific improvement", template: "What do you feel you need help with specifically to [improve existing result]?", purpose: "Use the improvement variant when the prospect already performs the activity.", delivery: "curious", use: "adapt", sourceRef: "A, A04, original characters [28088, 28700)" },
  { id: "I07", phase: "intent", label: "new activity goal", template: "What is your intent in looking at possibly starting [new activity]? What are you looking to get out of it?", purpose: "Use the new-activity variant rather than asking both intent openers.", delivery: "curious", use: "adapt", sourceRef: "A, A04, original characters [28655, 29247)" },
  { id: "I08", phase: "intent", label: "recap accuracy", template: "My colleague's notes say [goal, problem, impact]. Is that about right?", purpose: "Confirm the setter recap before entering emotional certainty.", delivery: "casual-curious", use: "adapt", sourceRef: "A, A04, original characters [29822, 30414)" },
  { id: "L01", phase: "logicalCertainty", label: "current process", template: "What are you doing now to [achieve tangible]?", purpose: "Identify the current process the instructor later connects to the problem.", delivery: "curious", use: "adapt", sourceRef: "A, A02, original characters [13454, 14049)" },
  { id: "L02", phase: "logicalCertainty", label: "process duration", template: "How long have you been doing it that way?", purpose: "Establish the history of the current approach.", delivery: "curious", use: "adapt", sourceRef: "A, A02, original characters [13614, 14216)" },
  { id: "L03", phase: "logicalCertainty", label: "process origin", template: "What caused you to use that approach in the first place?", purpose: "Identify its original rationale; instructor also calls this a doubt question.", delivery: "curious-skeptical", use: "adapt", sourceRef: "A, A02, original characters [13669, 14283)" },
  { id: "L04", phase: "logicalCertainty", label: "current satisfaction", template: "Besides [unmet result], do you like the approach you have now?", purpose: "Introduce both positive and negative aspects of the existing process.", delivery: "casual-curious", use: "adapt", sourceRef: "A, A02, original characters [14618, 15199)" },
  { id: "L05", phase: "logicalCertainty", label: "valued elements", template: "What do you like about it?", purpose: "Find what the prospect values in their present approach.", delivery: "curious", use: "adapt", sourceRef: "A, A02, original characters [14834, 15419)" },
  { id: "L06", phase: "logicalCertainty", label: "forced positive", template: "It cannot all be terrible if you have been using it. What do you like about it? Tell me one thing.", purpose: "Source forces the no-answer branch back into yes to appear unbiased.", delivery: "skeptical", use: "study_only", sourceRef: "A, A02, original characters [15749, 16326)" },
  { id: "L07", phase: "logicalCertainty", label: "change desired", template: "Is there anything you would change about either [process] or [results], if you could?", purpose: "Obtain a specific problem after discussing what works.", delivery: "skeptical", use: "adapt", sourceRef: "A, A02, original characters [15030, 15628)" },
  { id: "L08", phase: "logicalCertainty", label: "problem meaning", template: "What do you mean by that?", purpose: "Clarify the specific problem rather than accepting a label alone.", delivery: "curious", use: "adapt", sourceRef: "A, A02, original characters [16826, 17410)" },
  { id: "L09", phase: "logicalCertainty", label: "problem meaning", template: "How do you mean? Meaning what?", purpose: "Alternative short probes for the same clarification purpose.", delivery: "curious", use: "adapt", sourceRef: "A, A02, original characters [16852, 17435)" },
  { id: "L10", phase: "logicalCertainty", label: "problem duration", template: "How long has [specific problem] been going on?", purpose: "Establish the duration of the problem, distinct from process duration.", delivery: "curious", use: "adapt", sourceRef: "A, A02, original characters [16944, 17539)" },
  { id: "L11", phase: "logicalCertainty", label: "motivation impact", template: "Without assuming, has [problem despite effort] had an impact on your motivation to keep going?", purpose: "Fitness example of impact; do not import it into every industry.", delivery: "concern", use: "adapt", sourceRef: "A, A02, original characters [17484, 18079)" },
  { id: "L12", phase: "logicalCertainty", label: "business impact", template: "How has [low lead volume] affected your ability to hire a crew and expand?", purpose: "Business example of downstream operational impact.", delivery: "curious-concern", use: "adapt", sourceRef: "A, A02, original characters [19941, 20551)" },
  { id: "L13", phase: "logicalCertainty", label: "day to day impact", template: "Has [problem] affected your day-to-day life in any way?", purpose: "Business-opportunity example of personal impact.", delivery: "concern", use: "adapt", sourceRef: "A, A02, original characters [20938, 21524)" },
  { id: "L14", phase: "logicalCertainty", label: "impact detail", template: "How so, just so I understand?", purpose: "Get a concrete explanation after a yes to the impact question.", delivery: "curious", use: "adapt", sourceRef: "A, A02, original characters [21236, 21823)" },
  { id: "S01", phase: "setterTransition", label: "target value and horizon", template: "In an ideal world, where do you want to be in six months in terms of [relevant metric]?", purpose: "Establish a quantified target for the setter transition.", delivery: "curious", use: "adapt", sourceRef: "A, A03, original characters [22334, 22931)" },
  { id: "S02", phase: "setterTransition", label: "baseline gap", template: "How far are you from that now?", purpose: "Establish the baseline/gap; the source uses income qualification.", delivery: "curious", use: "adapt", sourceRef: "A, A03, original characters [22474, 23063)" },
  { id: "S03", phase: "setterTransition", label: "willingness to spend", template: "If there were a way to help you [move from baseline to target], would you be willing to invest in yourself if that is what it took?", purpose: "Source willingness-to-invest question; A conditions it on low qualification, B asks more broadly.", delivery: "casual-hypothetical", use: "adapt", sourceRef: "A, A03, original characters [23057, 23668)" },
  { id: "S04", phase: "setterTransition", label: "appointment interest", template: "I could connect you with [closer] to explore your situation and possible help. How does that sound?", purpose: "Ask permission to schedule the specialist/closer conversation.", delivery: "casual", use: "adapt", sourceRef: "A, A03, original characters [24185, 24764)" },
  { id: "S05", phase: "setterTransition", label: "appointment interest", template: "Would that be awful?", purpose: "Source alternate negative-form appointment check.", delivery: "casual", use: "adapt", sourceRef: "A, A03, original characters [24206, 24785)" },
  { id: "E01", phase: "emotionalCertainty", label: "reason for external help", template: "Besides [problem], what is the main reason for looking at [advanced help] rather than doubling down on [current approach]?", purpose: "Rationale question; instructor seeks the prospect's argument against DIY/status quo.", delivery: "curious-skeptical", use: "adapt", sourceRef: "A, A05, original characters [31004, 31594)" },
  { id: "E02", phase: "emotionalCertainty", label: "looked before", template: "Before we spoke, were you looking for other ways to get [help/result], or what were you doing about that?", purpose: "Open the previous-effort decision tree.", delivery: "curious", use: "adapt", sourceRef: "A, A05, original characters [33457, 34047)" },
  { id: "E03", phase: "emotionalCertainty", label: "previous barrier", template: "What prevented you? Why not?", purpose: "When they were not looking, or looked but did not proceed, identify the reason.", delivery: "curious-skeptical", use: "adapt", sourceRef: "A, A05, original characters [34129, 34711)" },
  { id: "E04", phase: "emotionalCertainty", label: "changed circumstances", template: "What shifted for you now that has you looking, given that [barrier] prevented you before?", purpose: "Explore what changed after the previous barrier.", delivery: "skeptical", use: "adapt", sourceRef: "A, A05, original characters [34544, 35133)" },
  { id: "E05", phase: "emotionalCertainty", label: "previous purchase or action", template: "Did you actually move forward with anything, or what ended up happening?", purpose: "Distinguish research from a purchased/implemented solution.", delivery: "curious", use: "adapt", sourceRef: "A, A05, original characters [35257, 35856)" },
  { id: "E06", phase: "emotionalCertainty", label: "prior result", template: "Did you get a good result or a bad result?", purpose: "Branch based on the prior solution's result.", delivery: "curious", use: "adapt", sourceRef: "A, A05, original characters [36644, 37257)" },
  { id: "E07", phase: "emotionalCertainty", label: "ideal criteria", template: "What would you need to see in something this time to feel it could get you results, given what happened last time?", purpose: "Capture ideal criteria after a disappointing result.", delivery: "curious", use: "adapt", sourceRef: "A, A05, original characters [37126, 37735)" },
  { id: "E08", phase: "emotionalCertainty", label: "remaining bottleneck", template: "If you got a good result last time, what has you looking for more advanced help this time?", purpose: "Identify the new bottleneck or reason to change a previously successful approach.", delivery: "curious", use: "adapt", sourceRef: "A, A05, original characters [38030, 38619)" },
  { id: "F01", phase: "emotionalCertainty", label: "analogy permission", template: "Can I offer you a perspective?", purpose: "Permission to introduce the optional runner/lion analogy.", delivery: "casual", use: "adapt", sourceRef: "A, A06, original characters [39123, 39712)" },
  { id: "F02", phase: "emotionalCertainty", label: "analogy familiarity", template: "Have you heard the Usain Bolt analogy?", purpose: "Source setup for the pull-and-consequence analogy; name normalized from ASR.", delivery: "casual", use: "study_only", sourceRef: "A, A06, original characters [39159, 39756)" },
  { id: "F03", phase: "emotionalCertainty", label: "positive future", template: "If there were a way to help with [goal and impact], what would tangibly be different for you?", purpose: "Start the positive future picture, not merely a numeric goal.", delivery: "curious-upward", use: "adapt", sourceRef: "A, A06, original characters [40313, 40923)" },
  { id: "F04", phase: "emotionalCertainty", label: "personal word meaning", template: "What do you mean by [free]?", purpose: "Clarify the prospect's own emotionally significant term.", delivery: "curious", use: "adapt", sourceRef: "A, A06, original characters [40781, 41364)" },
  { id: "F05", phase: "emotionalCertainty", label: "specific situation", template: "In what situations do you think your confidence would improve most?", purpose: "Turn a general feeling into a specific scene.", delivery: "curious", use: "adapt", sourceRef: "A, A06, original characters [40874, 41481)" },
  { id: "F06", phase: "emotionalCertainty", label: "future location", template: "Where would you want to travel?", purpose: "Concrete location probe in the travel example.", delivery: "curious-upward", use: "adapt", sourceRef: "A, A06, original characters [41738, 42328)" },
  { id: "F07", phase: "emotionalCertainty", label: "future setting", template: "Would you stay in a hotel or an Airbnb? Where would you stay?", purpose: "Concrete setting in the source travel visualization.", delivery: "curious-upward", use: "adapt", sourceRef: "A, A06, original characters [41811, 42397)" },
  { id: "F08", phase: "emotionalCertainty", label: "future people", template: "Who would you want to take with you?", purpose: "Identify people involved in the desired outcome.", delivery: "curious-upward", use: "adapt", sourceRef: "A, A06, original characters [42004, 42599)" },
  { id: "F09", phase: "emotionalCertainty", label: "positive feeling", template: "How would that feel, with [their described scene]?", purpose: "Ask about the meaning/feeling of the concrete future.", delivery: "curious-upward", use: "adapt", sourceRef: "A, A06, original characters [42133, 42717)" },
  { id: "F10", phase: "emotionalCertainty", label: "business future", template: "What would tangibly be different for the business at that point?", purpose: "Start B2B future pacing with the business, not imposed private desires.", delivery: "curious", use: "adapt", sourceRef: "A, A06, original characters [42697, 43297)" },
  { id: "F11", phase: "emotionalCertainty", label: "business growth effect", template: "How do you feel that would affect the company's growth?", purpose: "Explore the business outcome of a proposed change.", delivery: "curious", use: "adapt", sourceRef: "A, A06, original characters [42889, 43481)" },
  { id: "F12", phase: "emotionalCertainty", label: "owner future", template: "As the owner, what would be different for you at that point?", purpose: "Move from a business change to owner meaning where appropriate.", delivery: "curious", use: "adapt", sourceRef: "A, A06, original characters [43450, 44059)" },
  { id: "C01", phase: "emotionalCertainty", label: "consequence", template: "What happens if you stay on [current trajectory/problem] for the next two days, two weeks, two months, even two years?", purpose: "Source negative future/consequence question.", delivery: "curious-downward", use: "adapt", sourceRef: "A, A06, original characters [45815, 46397)" },
  { id: "C02", phase: "emotionalCertainty", label: "consequence detail", template: "What sports would you not be able to play?", purpose: "Specific consequence probe in the fitness/family example.", delivery: "concern", use: "adapt", sourceRef: "A, A06, original characters [46396, 47004)" },
  { id: "C03", phase: "emotionalCertainty", label: "consequence setting", template: "Do you have a field nearby?", purpose: "Source situational detail for the imagined consequence.", delivery: "concern", use: "adapt", sourceRef: "A, A06, original characters [46590, 47181)" },
  { id: "C04", phase: "emotionalCertainty", label: "owner consequence", template: "What might that mean for you as the owner?", purpose: "Translate business consequence into owner consequence.", delivery: "concern", use: "adapt", sourceRef: "A, A06, original characters [47411, 48017)" },
  { id: "C05", phase: "emotionalCertainty", label: "negative feeling", template: "How would you feel at that point?", purpose: "Additional feeling question; A says it may be skipped for B2B.", delivery: "concern", use: "adapt", sourceRef: "A, A06, original characters [47807, 48409)" },
  { id: "C06", phase: "emotionalCertainty", label: "regret", template: "What is the day-to-day feeling three, six, or twelve months from now, knowing you could have been [desired outcome] but were not?", purpose: "B adds a regret-directed second consequence question.", delivery: "confident-slow", use: "study_only", sourceRef: "B, B03, original characters [68653, 69243)" },
  { id: "P01", phase: "pitch", label: "commitment to change", template: "Are you willing to settle for [stated consequence]?", purpose: "First source commitment: not accepting the current trajectory.", delivery: "confident", use: "adapt", sourceRef: "A, A07, original characters [50537, 51131)" },
  { id: "P02", phase: "pitch", label: "timing reason", template: "Why draw the line and make the change now rather than starting later?", purpose: "Second source commitment: timing/reason to act.", delivery: "skeptical", use: "adapt", sourceRef: "A, A07, original characters [50650, 51221)" },
  { id: "P03", phase: "pitch", label: "responsibility", template: "Whose responsibility is it to make that change?", purpose: "Third source commitment: personal responsibility; B omits for some CEOs.", delivery: "confident", use: "adapt", sourceRef: "A, A07, original characters [50980, 51583)" },
  { id: "P04", phase: "pitch", label: "pitch permission", template: "Would it be appropriate to put together a game plan, or what would you like to do from here?", purpose: "Get permission to present the offer.", delivery: "casual-confident", use: "adapt", sourceRef: "A, A07, original characters [51886, 52507)" },
  { id: "P05", phase: "pitch", label: "pillar relevance", template: "Do you feel [pillar tied to their problem] would be helpful for you?", purpose: "Check relevance after one pillar.", delivery: "casual", use: "adapt", sourceRef: "A, A07, original characters [53116, 53718)" },
  { id: "P06", phase: "pitch", label: "pillar comprehension", template: "Does that make sense?", purpose: "Comprehension check after explaining a pillar.", delivery: "casual", use: "adapt", sourceRef: "A, A07, original characters [53948, 54528)" },
  { id: "P07", phase: "pitch", label: "perceived fit", template: "Based on what we covered, do you feel this would get you to [goal]?", purpose: "Ask the prospect for their assessment of the proposed solution.", delivery: "confident", use: "adapt", sourceRef: "A, A07, original characters [54620, 55237)" },
  { id: "P08", phase: "pitch", label: "key value driver", template: "Why? What do you think would help you most?", purpose: "Ask for the most important pillar and their reasoning.", delivery: "curious", use: "adapt", sourceRef: "A, A07, original characters [54875, 55487)" },
  { id: "P09", phase: "pitch", label: "value personal meaning", template: "What would having [key pillar] do for you personally?", purpose: "Relate the offer benefit back to personal meaning.", delivery: "curious", use: "adapt", sourceRef: "A, A07, original characters [55241, 55844)" },
  { id: "P10", phase: "pitch", label: "decision", template: "The total investment for [offer/outcome framing] is [price]. How would you like to proceed?", purpose: "Source price drop and decision request; no unapproved prices.", delivery: "casual-confident", use: "adapt", sourceRef: "A, A07, original characters [55886, 56475)" },
  { id: "P11", phase: "pitch", label: "note taking", template: "Do you have a pen and paper?", purpose: "Invite note-taking before the pillar pitch.", delivery: "casual", use: "adapt", sourceRef: "B, B04, original characters [74270, 74857)" },
  { id: "P12", phase: "pitch", label: "pillar relevance", template: "Do you see why that is there?", purpose: "Alternative relevance check linking the pillar to a stated need.", delivery: "casual", use: "adapt", sourceRef: "B, B04, original characters [76727, 77311)" },
  { id: "M01", phase: "mirror", label: "intended answer type", template: "What answer type was the original question supposed to obtain?", purpose: "Instructor's design question for creating a mirror, not prospect-facing.", delivery: "training", use: "private_training", sourceRef: "A, A09, original characters [69666, 70256)" },
  { id: "M02", phase: "mirror", label: "current limitation", template: "What would making more money allow you to do that you cannot do now?", purpose: "Experience mirror after a repeated general money goal.", delivery: "curious", use: "adapt", sourceRef: "A, A09, original characters [73137, 73743)" },
  { id: "M03", phase: "mirror", label: "future effect", template: "How would [achieving goal] affect other areas of your life?", purpose: "Future mirror when the answer only repeats the outcome.", delivery: "curious", use: "adapt", sourceRef: "A, A09, original characters [74301, 74925)" },
  { id: "M04", phase: "mirror", label: "specific improvement", template: "What do you feel you need to improve most to [desired result]?", purpose: "Alternative tangible question in the source mirror exercise.", delivery: "curious", use: "adapt", sourceRef: "B, B09, original characters [133568, 134181)" },
  { id: "M05", phase: "mirror", label: "specific improvement", template: "In conversations that do not move forward, what one or two things could you improve to change that outcome?", purpose: "Second tangible mirror anchored to failed conversations.", delivery: "curious", use: "adapt", sourceRef: "B, B09, original characters [133949, 134543)" },
  { id: "M06", phase: "mirror", label: "mirror design", template: "What type of answer am I looking for? What are examples of it? What other questions could obtain those examples?", purpose: "The three-step mirror design exercise.", delivery: "training", use: "private_training", sourceRef: "B, B09, original characters [131868, 132464)" },
  { id: "O01", phase: "objection", label: "hypothetical value", template: "Money aside, if I gave you the full [price], would you actually do it?", purpose: "Source isolates perceived value before money logistics.", delivery: "casual", use: "adapt", sourceRef: "A, A11, original characters [83683, 84269)" },
  { id: "O02", phase: "objection", label: "value reason", template: "Why would you do it?", purpose: "Ask prospect to explain the hypothetical value judgment.", delivery: "curious", use: "adapt", sourceRef: "A, A11, original characters [83824, 84400)" },
  { id: "O03", phase: "objection", label: "value personal effect", template: "What would [valued component] do for you personally?", purpose: "Source re-establishes value before addressing the constraint.", delivery: "curious", use: "adapt", sourceRef: "A, A11, original characters [84073, 84671)" },
  { id: "O04", phase: "objection", label: "payment timing constraint", template: "Is it the initial investment, or would breaking it up make it more manageable financially?", purpose: "Source tests upfront amount vs installment logistics.", delivery: "casual", use: "adapt", sourceRef: "A, A11, original characters [84489, 85075)" },
  { id: "O05", phase: "objection", label: "available savings", template: "Cash on hand, expenses aside, what do you have saved up?", purpose: "Source asks available savings to shape a payment plan; replace with appropriate business budget in own script.", delivery: "casual", use: "study_only", sourceRef: "A, A11, original characters [84785, 85370)" },
  { id: "O06", phase: "objection", label: "plan affordability", template: "Would [specific payment plan] work within your budgetary constraints?", purpose: "Check affordability of the stated plan.", delivery: "casual", use: "adapt", sourceRef: "A, A11, original characters [85455, 86064)" },
  { id: "O07", phase: "objection", label: "decision after money", template: "Given your view of the value and that this plan fits your budget, how would you like to proceed?", purpose: "Source asks for the decision again after money discussion.", delivery: "casual", use: "adapt", sourceRef: "A, A11, original characters [85785, 86378)" },
  { id: "O08", phase: "objection", label: "value without time", template: "Time aside, if you had the time, would you do it? Do you feel it would help you reach [goal]?", purpose: "Source isolates value again before handling time.", delivery: "casual", use: "adapt", sourceRef: "A, A11, original characters [86778, 87362)" },
  { id: "O09", phase: "objection", label: "identity choice", template: "Which of those two people do you want to be?", purpose: "Source time reframe asks the prospect to identify with its preferred alternative.", delivery: "confident", use: "study_only", sourceRef: "A, A11, original characters [88474, 89077)" },
  { id: "O10", phase: "objection", label: "defended identity", template: "Why? You do not have to be that person.", purpose: "Source pushback prompts defense of the identity choice.", delivery: "skeptical", use: "study_only", sourceRef: "A, A11, original characters [88637, 89232)" },
  { id: "O11", phase: "objection", label: "identity consequence", template: "What would happen if you chose the first person's approach instead?", purpose: "Source consequence attaches pain to its disfavored identity.", delivery: "concern", use: "study_only", sourceRef: "A, A11, original characters [88888, 89492)" },
  { id: "O12", phase: "objection", label: "reframe cta", template: "What decision do you need to make to put yourself in the best position to [goal]?", purpose: "Source commitment/action question after reframing.", delivery: "confident", use: "adapt", sourceRef: "A, A11, original characters [89404, 90011)" },
  { id: "O13", phase: "objection", label: "value with partner approval", template: "Partner aside, if they were on board, would you do it and feel it could get you to [goal]?", purpose: "Source value-isolation step for partner objection.", delivery: "casual", use: "adapt", sourceRef: "A, A11, original characters [93624, 94203)" },
  { id: "O14", phase: "objection", label: "bypass partner", template: "If your partner says no, would you do it anyway or give up on [goal]?", purpose: "Source false-binary partner challenge; not an approved commercial question.", delivery: "skeptical", use: "study_only", sourceRef: "A, A11, original characters [94299, 94876)" },
  { id: "O15", phase: "objection", label: "bypass justification", template: "Why would you do it anyway?", purpose: "Source asks prospect to defend proceeding without partner.", delivery: "skeptical", use: "study_only", sourceRef: "A, A11, original characters [94628, 95207)" },
  { id: "O16", phase: "objection", label: "crown frame setup", template: "Have you heard the saying, heavy is the head that wears the crown?", purpose: "Introduction to source responsibility reframe.", delivery: "casual", use: "study_only", sourceRef: "A, A11, original characters [94959, 95557)" },
  { id: "O17", phase: "objection", label: "who does work", template: "Who will actually go through the training and do the work, you or your partner?", purpose: "Source personal-responsibility framing.", delivery: "curious", use: "study_only", sourceRef: "A, A11, original characters [95623, 96237)" },
  { id: "O18", phase: "objection", label: "responsibility for preparation", template: "Whose responsibility is it to put you in the best position to learn the skill?", purpose: "Source responsibility conclusion.", delivery: "confident", use: "study_only", sourceRef: "A, A11, original characters [95750, 96354)" },
  { id: "O19", phase: "objection", label: "delegation fairness", template: "Would it be fair to put that responsibility on anybody but yourself?", purpose: "Source attempts to invalidate a stakeholder decision.", delivery: "skeptical", use: "study_only", sourceRef: "A, A11, original characters [96013, 96607)" },
  { id: "O20", phase: "objection", label: "responsibility defense", template: "Why would that not be fair?", purpose: "Source pushback to defend responsibility claim.", delivery: "skeptical", use: "study_only", sourceRef: "A, A11, original characters [96233, 96814)" },
  { id: "O21", phase: "objection", label: "career consequence", template: "What do you think would happen to your career then?", purpose: "Consequence after the crown responsibility frame.", delivery: "concern", use: "study_only", sourceRef: "A, A11, original characters [97019, 97629)" },
  { id: "O22", phase: "objection", label: "certainty agreement", template: "Ultimately, what you are seeking is certainty that you will get the result. Is that right?", purpose: "Agreeance statement converts risk/commitment to lack of certainty in the source.", delivery: "casual", use: "adapt", sourceRef: "A, A11, original characters [99290, 99892)" },
  { id: "O23", phase: "objection", label: "analogy worker choice", template: "Is [the worker example] pursuing uncertainty/adventure or certainty/safety?", purpose: "First half of A's worked certainty analogy.", delivery: "curious", use: "study_only", sourceRef: "A, A11, original characters [102157, 102763)" },
  { id: "O24", phase: "objection", label: "analogy entrepreneur choice", template: "Is [the entrepreneur example] pursuing safety or taking a chance on themselves?", purpose: "Second half of A's worked certainty analogy.", delivery: "curious", use: "study_only", sourceRef: "A, A11, original characters [102469, 103083)" },
  { id: "O25", phase: "objection", label: "perspective link", template: "Can you see how making decisions by seeking certainty could have contributed to your current situation?", purpose: "Source links the selected frame to past outcomes.", delivery: "skeptical", use: "adapt", sourceRef: "A, A11, original characters [102736, 103316)" },
  { id: "O26", phase: "objection", label: "decision pattern consequence", template: "What happens if you keep using that same way of deciding for [time horizon]?", purpose: "Consequence inside the source certainty reframe.", delivery: "concern", use: "adapt", sourceRef: "A, A11, original characters [103009, 103626)" },
  { id: "O27", phase: "objection", label: "analogy weather uncertainty", template: "Has the weather app ever been wrong?", purpose: "First concrete question in B's fully described beach analogy.", delivery: "casual", use: "study_only", sourceRef: "B, B05, original characters [99957, 100539)" },
  { id: "O28", phase: "objection", label: "analogy perfect certainty", template: "If I required guaranteed perfect weather, would I ever go to the beach?", purpose: "Second question in B's beach certainty frame.", delivery: "curious", use: "study_only", sourceRef: "B, B05, original characters [100158, 100757)" },
  { id: "O29", phase: "objection", label: "analogy transfer", template: "If I required a guaranteed result before investing in skills, would I ever invest and learn them?", purpose: "Source analogy transfer from beach to purchasing.", delivery: "curious", use: "study_only", sourceRef: "B, B05, original characters [100546, 101165)" },
  { id: "O30", phase: "objection", label: "past certainty barrier", template: "Could that be why you have not invested in [solution] before now?", purpose: "Source links certainty-seeking to previous inaction.", delivery: "skeptical", use: "adapt", sourceRef: "B, B05, original characters [100771, 101387)" },
  { id: "O31", phase: "objection", label: "chosen mindset", template: "What mindset would put you in the best position to pursue [goal], rather than requiring certainty first?", purpose: "Source CTA can ask for a mindset change before another purchase request.", delivery: "confident", use: "private_training", sourceRef: "B, B05, original characters [103450, 104060)" },
  { id: "D01", phase: "identityAndTaxonomy", label: "deceptive status deflation", template: "A million a week?", purpose: "Source intentionally mishears a monthly number as weekly to lower the prospect's status.", delivery: "skeptical", use: "study_only", sourceRef: "A, A10, original characters [80241, 80817)" },
  { id: "D02", phase: "identityAndTaxonomy", label: "unsupported benchmark", template: "Only [number]? Why so low?", purpose: "Source status challenge without establishing a relevant benchmark.", delivery: "skeptical", use: "study_only", sourceRef: "A, A10, original characters [81396, 81856)" },
  { id: "D03", phase: "identityAndTaxonomy", label: "family identity shame", template: "Who would that make you as a father, knowing you could have acted but did not?", purpose: "Source future-negative identity/shame question.", delivery: "concern", use: "study_only", sourceRef: "A, A12, original characters [117845, 118458)" },
  { id: "D04", phase: "identityAndTaxonomy", label: "negative self label", template: "Who would that make you as a person?", purpose: "Source negative identity labeling after imagined regret.", delivery: "concern", use: "study_only", sourceRef: "A, A12, original characters [119140, 119748)" },
  { id: "D05", phase: "identityAndTaxonomy", label: "future positive identity", template: "Who would that make you as a person, being someone who took the opportunity and provided for your family?", purpose: "Source future-positive identity framing.", delivery: "curious", use: "study_only", sourceRef: "A, A12, original characters [120434, 121046)" },
  { id: "D06", phase: "identityAndTaxonomy", label: "identity frame target", template: "What do you want to be making monthly?", purpose: "Target question in the optional identity frame.", delivery: "curious", use: "private_training", sourceRef: "B, B10, original characters [145187, 145784)" },
  { id: "D07", phase: "identityAndTaxonomy", label: "identity frame baseline", template: "Where are you now? How far are you from [target]?", purpose: "Baseline question in the optional identity frame.", delivery: "curious", use: "private_training", sourceRef: "B, B10, original characters [145342, 145922)" },
  { id: "D08", phase: "identityAndTaxonomy", label: "identity frame contrast", template: "Is it worth keeping the same mindset and [skill set/process] that got you here but is not getting you there?", purpose: "Core source contrast in the optional identity frame.", delivery: "slow", use: "study_only", sourceRef: "B, B10, original characters [146181, 146777)" },
  { id: "D09", phase: "identityAndTaxonomy", label: "identity frame defense", template: "Why is it not worth keeping that same way of thinking?", purpose: "Source pushback asks defense of changing the old identity/process.", delivery: "skeptical", use: "study_only", sourceRef: "B, B10, original characters [146346, 146927)" },
  { id: "D10", phase: "identityAndTaxonomy", label: "identity frame consequence", template: "What happens if you keep the same mindset and [skill set/process]?", purpose: "Source consequence for maintaining the current approach.", delivery: "slow", use: "study_only", sourceRef: "B, B10, original characters [147255, 147856)" },
  { id: "D11", phase: "identityAndTaxonomy", label: "identity commitment", template: "Are you committed to doing what it takes to become the person who can [goal]?", purpose: "Source commitment to a desired identity; own version must bound commitments.", delivery: "confident", use: "private_training", sourceRef: "B, B10, original characters [147749, 148353)" },
  { id: "D12", phase: "identityAndTaxonomy", label: "self selected needs", template: "What are the top two needs you value right now?", purpose: "Self-application of the six-human-needs lens.", delivery: "reflection", use: "private_training", sourceRef: "B, B11, original characters [168279, 168875)" },
  { id: "D13", phase: "identityAndTaxonomy", label: "needs counterfactual", template: "How would your motivation change if you valued uncertainty rather than certainty?", purpose: "Source reflective contrast, not a diagnostic test.", delivery: "reflection", use: "private_training", sourceRef: "B, B11, original characters [168518, 169125)" },
  { id: "T01", phase: "training", label: "answer category", template: "What is the answer type you want?", purpose: "Question-design exercise before writing a script.", delivery: "training", use: "private_training", sourceRef: "B, B08, original characters [121919, 122505)" },
  { id: "T02", phase: "training", label: "context variables", template: "What context needs to be added to get that answer?", purpose: "Contextualization exercise after choosing the answer category.", delivery: "training", use: "private_training", sourceRef: "B, B08, original characters [128268, 128870)" },
  { id: "T03", phase: "training", label: "no show by hour", template: "When is your highest no-show time?", purpose: "Source diary analysis question.", delivery: "training", use: "private_training", sourceRef: "B, B07, original characters [115766, 116359)" },
  { id: "T04", phase: "training", label: "next work block", template: "Which useful sales activity can I do while no appointment is occurring?", purpose: "Normalized source productivity reflection, not a command to multitask unsafely.", delivery: "training", use: "private_training", sourceRef: "B, B07, original characters [119332, 119919)" },
  { id: "T05", phase: "training", label: "self selected practice", template: "What will you actively do week to week and month to month to build self-esteem?", purpose: "Source links confidence to practiced effort and skill, not only money.", delivery: "reflection", use: "private_training", sourceRef: "B, B24, original characters [310241, 310653)" },
  { id: "T06", phase: "training", label: "process consistency", template: "Would you change the whole process because a few people declined in a short period?", purpose: "Source warning about overreacting to small samples.", delivery: "reflection", use: "private_training", sourceRef: "B, B24, original characters [308099, 308720)" },
  { id: "U01", phase: "followUp", label: "nurture permission", template: "Would it help to review [relevant resource] and reconnect before scheduling the longer call?", purpose: "Setter nurture-before-close route.", delivery: "casual", use: "adapt", sourceRef: "B, B17, original characters [225012, 225593)" },
  { id: "U02", phase: "followUp", label: "interest now", template: "Are you still looking for help with [goal], or have you already found something?", purpose: "Reconfirm active interest on the agreed callback.", delivery: "casual", use: "adapt", sourceRef: "B, B17, original characters [228450, 229035)" },
  { id: "U03", phase: "followUp", label: "resource reviewed", template: "Did you have a chance to go through the training I sent?", purpose: "Check whether the agreed resource was reviewed.", delivery: "curious", use: "adapt", sourceRef: "B, B17, original characters [229048, 229656)" },
  { id: "U04", phase: "followUp", label: "resource takeaway", template: "What did you take away from it?", purpose: "Elicit the prospect's own takeaway rather than assuming persuasion.", delivery: "curious", use: "adapt", sourceRef: "B, B17, original characters [229260, 229850)" },
  { id: "U05", phase: "followUp", label: "resource application", template: "How do you feel [takeaway] would apply to you?", purpose: "Connect the selected resource to the prospect's situation.", delivery: "curious", use: "adapt", sourceRef: "B, B17, original characters [229973, 230579)" },
  { id: "U06", phase: "followUp", label: "resource noncompletion tease", template: "What happened, did you get kidnapped?", purpose: "Source teasing response to not watching; no live use by default.", delivery: "teasing", use: "study_only", sourceRef: "B, B17, original characters [229687, 230273)" },
  { id: "U07", phase: "followUp", label: "followup change", template: "What has changed since we spoke? What is the plan now?", purpose: "Update the situation on a follow-up instead of replaying all discovery.", delivery: "casual", use: "adapt", sourceRef: "B, B18, original characters [241056, 241630)" },
  { id: "U08", phase: "followUp", label: "funds progress", template: "How are you doing on collecting the funds to [buy]?", purpose: "Source payment-readiness follow-up; use agreed business constraints, not pressure.", delivery: "casual", use: "study_only", sourceRef: "B, B18, original characters [241248, 241828)" },
  { id: "U09", phase: "followUp", label: "resource feedback", template: "How was the resource for you?", purpose: "Closer follow-up checks relevance of nurture material.", delivery: "casual", use: "adapt", sourceRef: "B, B18, original characters [240775, 241355)" },
  { id: "R01", phase: "referral", label: "client experience", template: "How do you feel about [purchase/progress]?", purpose: "Start a success-point check-in.", delivery: "casual", use: "adapt", sourceRef: "B, B19, original characters [248747, 249327)" },
  { id: "R02", phase: "referral", label: "client next expectation", template: "What are you looking forward to most?", purpose: "Understand the client's next positive expectation.", delivery: "curious", use: "adapt", sourceRef: "B, B19, original characters [248861, 249461)" },
  { id: "R03", phase: "referral", label: "possible referral", template: "Who else do you know who may be facing a similar problem and whom we might help?", purpose: "Source referral request.", delivery: "casual", use: "adapt", sourceRef: "B, B19, original characters [248917, 249502)" },
  { id: "R04", phase: "referral", label: "referral pressure", template: "Have you thought about it? Who else do you really know?", purpose: "Source insistence after no answer; not a mandatory live branch.", delivery: "skeptical", use: "study_only", sourceRef: "B, B19, original characters [249261, 249851)" },
  { id: "R05", phase: "referral", label: "referral names", template: "What are their names?", purpose: "Source identifies possible referral contacts.", delivery: "casual", use: "adapt", sourceRef: "B, B19, original characters [249552, 250143)" },
  { id: "R06", phase: "referral", label: "referral fit", template: "Why do you feel we could help them?", purpose: "Explore fit rather than collecting any contact.", delivery: "curious", use: "adapt", sourceRef: "B, B19, original characters [249615, 250214)" },
  { id: "R07", phase: "referral", label: "introduction permission", template: "Would you make an introduction so we can have a conversation and see whether help makes sense?", purpose: "Source introduction request, normalized to an explicit invitation.", delivery: "casual", use: "adapt", sourceRef: "B, B19, original characters [249866, 250460)" },
  { id: "X01", phase: "upsellSetting", label: "current product feedback", template: "What has your feedback been so far?", purpose: "Upsell setting begins with experience of the current product.", delivery: "casual", use: "adapt", sourceRef: "B, B20, original characters [256945, 257537)" },
  { id: "X02", phase: "upsellSetting", label: "delivered results", template: "What results have you gotten so far from [current product]?", purpose: "Establish delivered results before any expansion.", delivery: "curious", use: "adapt", sourceRef: "B, B20, original characters [257111, 257714)" },
  { id: "X03", phase: "upsellSetting", label: "next goal", template: "What is next for you? What is the next goal?", purpose: "Open the next goal, not a replay of solved original pain.", delivery: "curious", use: "adapt", sourceRef: "B, B20, original characters [257728, 258320)" },
  { id: "X04", phase: "upsellSetting", label: "remaining gap", template: "What has prevented you from reaching [next goal], even with the current product?", purpose: "Identify the remaining gap.", delivery: "curious", use: "adapt", sourceRef: "B, B20, original characters [258195, 258797)" },
  { id: "X05", phase: "upsellSetting", label: "remaining gap detail", template: "What do you mean by that?", purpose: "Probe the new gap before diagnostic expansion.", delivery: "curious", use: "adapt", sourceRef: "B, B20, original characters [258647, 259231)" },
  { id: "X06", phase: "upsellSetting", label: "diagnostic permission", template: "Would you role-play that situation with me for a moment?", purpose: "Sales-training example of the diagnostic/expansion stage.", delivery: "casual", use: "adapt", sourceRef: "B, B20, original characters [259868, 260458)" },
  { id: "X07", phase: "upsellSetting", label: "advanced help analogy", template: "Which of the three approaches in this example would reach the outcome fastest?", purpose: "Source books/videos/trainer analogy for advanced help.", delivery: "curious", use: "study_only", sourceRef: "B, B20, original characters [261647, 262245)" },
  { id: "X08", phase: "upsellSetting", label: "analogy justification", template: "Why the third person?", purpose: "Source asks the prospect to justify the analogy.", delivery: "curious", use: "study_only", sourceRef: "B, B20, original characters [261898, 262475)" },
  { id: "X09", phase: "upsellSetting", label: "expansion interest", template: "Would you be open to exploring more individualized help for [next goal]?", purpose: "Invite discussion of a distinct expansion offer.", delivery: "casual", use: "adapt", sourceRef: "B, B20, original characters [262776, 263353)" },
  { id: "X10", phase: "upsellSetting", label: "expansion handoff permission", template: "Would it help to connect with [specialist] to assess options and any applicable credit?", purpose: "Source handoff/credit framing; never invent credit or a no-extra-money promise.", delivery: "casual", use: "adapt", sourceRef: "B, B20, original characters [264393, 264996)" },
  { id: "X11", phase: "upsellSetting", label: "resource received", template: "Let me know whether the link opens.", purpose: "Source resource-delivery check; do not fabricate technical trouble to induce a click.", delivery: "casual", use: "adapt", sourceRef: "B, B20, original characters [265649, 266232)" },
  { id: "Y01", phase: "upsellClosing", label: "current wins", template: "What do you feel is going well?", purpose: "Upsell closer starts by reviewing genuine positives.", delivery: "casual", use: "adapt", sourceRef: "B, B21, original characters [276149, 276744)" },
  { id: "Y02", phase: "upsellClosing", label: "valued component", template: "What has been most helpful about [component]?", purpose: "Identify the component they value, using their language.", delivery: "curious", use: "adapt", sourceRef: "B, B21, original characters [276456, 277044)" },
  { id: "Y03", phase: "upsellClosing", label: "next help needed", template: "What do you want more help with to reach the next level?", purpose: "Elicit a new tangible in an upsell conversation.", delivery: "curious", use: "adapt", sourceRef: "B, B21, original characters [276804, 277409)" },
  { id: "Y04", phase: "upsellClosing", label: "next goal reason", template: "Why is [additional help] important to you now?", purpose: "Determine why the next goal matters now.", delivery: "curious", use: "adapt", sourceRef: "B, B21, original characters [278045, 278643)" },
  { id: "Y05", phase: "upsellClosing", label: "new future outcomes", template: "What do you hope [new capability] will allow you to do?", purpose: "Future pace the new goal.", delivery: "curious", use: "adapt", sourceRef: "B, B21, original characters [278684, 279284)" },
  { id: "Y06", phase: "upsellClosing", label: "new personal meaning", template: "What would achieving [new specific outcomes] do for you personally?", purpose: "Personal meaning of expansion.", delivery: "slow", use: "adapt", sourceRef: "B, B21, original characters [280065, 280662)" },
  { id: "Y07", phase: "upsellClosing", label: "new goal consequence", template: "You have achieved [first goal] and chosen [new goal]. What happens if that new goal is not reached?", purpose: "Source consequence must concern the new gap, not erase prior success.", delivery: "concern", use: "adapt", sourceRef: "B, B21, original characters [280898, 281501)" },
  { id: "Y08", phase: "upsellClosing", label: "upsell pitch permission", template: "Would it help to make a game plan for that next level?", purpose: "Permission to show a distinct upsell.", delivery: "casual", use: "adapt", sourceRef: "B, B21, original characters [282357, 282935)" },
  { id: "Y09", phase: "upsellClosing", label: "upsell fit", template: "Do you feel this new structure could get you from where you are to the next level?", purpose: "Ask assessment of the new offer.", delivery: "confident", use: "adapt", sourceRef: "B, B21, original characters [284620, 285241)" },
  { id: "Y10", phase: "upsellClosing", label: "upsell fit reason", template: "Why do you feel it would?", purpose: "Elicit reasoning about expansion fit.", delivery: "curious", use: "adapt", sourceRef: "B, B21, original characters [284758, 285347)" },
  { id: "Y11", phase: "upsellClosing", label: "upsell key pillar", template: "Of the new pillars, what would help most?", purpose: "Identify the new value driver.", delivery: "curious", use: "adapt", sourceRef: "B, B21, original characters [284847, 285458)" },
  { id: "V01", phase: "reviewedCall", label: "opening goal", template: "How can I help you?", purpose: "Reviewed call opener.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [123168, 123746)" },
  { id: "V02", phase: "reviewedCall", label: "specific improvement", template: "Can you give me more specifics? Which techniques do you want in your process?", purpose: "Reviewed call mirror after vague skill/tool-belt answer.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [124210, 124808)" },
  { id: "V03", phase: "reviewedCall", label: "industry", template: "What industry are you in?", purpose: "Industry clarification; the raw question is garbled and the answer identifies life insurance.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [124649, 125230)" },
  { id: "V04", phase: "reviewedCall", label: "current process", template: "What is your current process when speaking to a potential prospect?", purpose: "Reviewed call current-process question.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [124675, 125270)" },
  { id: "V05", phase: "reviewedCall", label: "process duration", template: "How long have you had that process?", purpose: "Reviewed call process duration.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [125514, 126108)" },
  { id: "V06", phase: "reviewedCall", label: "process origin", template: "Why do you do it in that fashion?", purpose: "Reviewed call rationale for using employer's script.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [126057, 126641)" },
  { id: "V07", phase: "reviewedCall", label: "valued elements", template: "What is working? What do you like about it?", purpose: "Reviewed call asks positives before deficiencies.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [126403, 126991)" },
  { id: "V08", phase: "reviewedCall", label: "change desired", template: "What would you change about the current structure or the results from the last month?", purpose: "Reviewed call change question.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [126820, 127443)" },
  { id: "V09", phase: "reviewedCall", label: "contact count period", template: "How many people have you actively spoken with about insurance in the past month?", purpose: "Reviewed call quantifies opportunity volume.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [127479, 128070)" },
  { id: "V10", phase: "reviewedCall", label: "sale count period", template: "How many sales did you make last month?", purpose: "Reviewed call denominator/numerator pair.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [127609, 128206)" },
  { id: "V11", phase: "reviewedCall", label: "sale count exactness", template: "When you say a handful, do you mean two, five, ten? How many?", purpose: "Reviewed call quantification mirror.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [127690, 128278)" },
  { id: "V12", phase: "reviewedCall", label: "prospect causal hypothesis", template: "What might you have said, or not said, that contributed to resistance?", purpose: "Reviewed call asks the prospect for their causal hypothesis, not established causality.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [128740, 129335)" },
  { id: "V13", phase: "reviewedCall", label: "observed objections", template: "What objections did you hear from those who did not buy?", purpose: "Reviewed call pivots to concrete observed objections.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [129447, 130034)" },
  { id: "V14", phase: "reviewedCall", label: "specific instance", template: "Give me an example of an instance where that happened.", purpose: "Reviewed call asks for an actual event rather than a general claim.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [130631, 131229)" },
  { id: "V15", phase: "reviewedCall", label: "similar script use estimate", template: "How many people use that script or a similar process?", purpose: "Reviewed call introduces sameness/market-resistance hypothesis.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [130866, 131457)" },
  { id: "V16", phase: "reviewedCall", label: "perceived sameness", template: "What do you think using the same script makes you sound like?", purpose: "Reviewed call invites the prospect to label the perception.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [131557, 132158)" },
  { id: "V17", phase: "reviewedCall", label: "hypothetical additional sales", template: "How many additional sales do you think could have been made with less resistance?", purpose: "Reviewed call hypothetical missed-opportunity estimate; not observed lost revenue.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [132096, 132709)" },
  { id: "V18", phase: "reviewedCall", label: "commission per sale", template: "What is the average commission per sale?", purpose: "Reviewed call unit value appears as a garbled question/answer span.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [134478, 135062)" },
  { id: "V19", phase: "reviewedCall", label: "target monthly commission", template: "What monthly commissions do you want to reach?", purpose: "Reviewed call target.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [134772, 135392)" },
  { id: "V20", phase: "reviewedCall", label: "income baseline gap", template: "How far are you from that now?", purpose: "Reviewed call requests a specific baseline after pretty far.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [134928, 135509)" },
  { id: "V21", phase: "reviewedCall", label: "prior role income", template: "What were you making in HVAC, compared with now?", purpose: "Reviewed call prior-role comparison; HVAC normalized from Hback.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [135171, 135759)" },
  { id: "V22", phase: "reviewedCall", label: "resource reviewed", template: "Did you get a chance to go through the interview sent beforehand?", purpose: "Reviewed call prior nurture material.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [135300, 135909)" },
  { id: "V23", phase: "reviewedCall", label: "testimonial takeaway", template: "What did you take away from that process compared with yours?", purpose: "Reviewed call asks prospect to assess a testimonial, not adopt its result as guaranteed.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [135667, 136266)" },
  { id: "V24", phase: "reviewedCall", label: "reason for external help", template: "Why seek advanced training rather than simply make more dials?", purpose: "Reviewed call rationale; prospect identifies paid-lead economics.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [136383, 136982)" },
  { id: "V25", phase: "reviewedCall", label: "confirmed label efficiency", template: "So, efficiency?", purpose: "Seller-proposed label explicitly confirmed by prospect; record as confirmed paraphrase, not initially prospect-originated.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [136770, 137349)" },
  { id: "V26", phase: "reviewedCall", label: "prior training duration", template: "How long did you do that training?", purpose: "Reviewed call previous-solution duration.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [137919, 138503)" },
  { id: "V27", phase: "reviewedCall", label: "prior solution result", template: "What results did you get from that approach?", purpose: "Reviewed call previous-solution outcome.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [138033, 138643)" },
  { id: "V28", phase: "reviewedCall", label: "personal investment history", template: "Besides company-provided training, have you done anything else yourself?", purpose: "Reviewed call distinguishes employer-provided support from personal buying history.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [138448, 139065)" },
  { id: "V29", phase: "reviewedCall", label: "ideal criteria", template: "What are you looking for in a training program? What are your ideal criteria?", purpose: "Reviewed call pivots to criteria after an explanation for prior inaction.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [140280, 140877)" },
  { id: "V30", phase: "reviewedCall", label: "support requirements", template: "What type of support helps you learn best?", purpose: "Reviewed call unpacks one-on-one support rather than assuming its meaning.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [140863, 141469)" },
  { id: "V31", phase: "reviewedCall", label: "criterion priority", template: "Why is that support/accountability important to you now?", purpose: "Reviewed call criterion priority; prospect wants faster progress and feedback.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [142643, 143243)" },
  { id: "V32", phase: "reviewedCall", label: "target horizon", template: "In what time frame do you want to reach that?", purpose: "Reviewed call future target horizon.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [143224, 143823)" },
  { id: "V33", phase: "reviewedCall", label: "target reason", template: "Why [50,000] specifically?", purpose: "Reviewed call asks meaning behind the selected target.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [144159, 144729)" },
  { id: "V34", phase: "reviewedCall", label: "positive future", template: "What would you do with the additional income?", purpose: "Reviewed call positive future scope.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [144654, 145254)" },
  { id: "V35", phase: "reviewedCall", label: "school goal detail", template: "When you say schools, do you mean private schools?", purpose: "Reviewed call clarification; preceding alternative garbled in the transcript.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [145349, 145968)" },
  { id: "V36", phase: "reviewedCall", label: "cost units", template: "Is that cost per child or in total?", purpose: "Reviewed call unit/denominator clarification.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [145591, 146167)" },
  { id: "V37", phase: "reviewedCall", label: "college savings goal", template: "How much do you want to set aside for college?", purpose: "Reviewed call savings goal; not live financial advice.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [146551, 147157)" },
  { id: "V38", phase: "reviewedCall", label: "savings gap", template: "How far are you from that savings target now?", purpose: "Reviewed call gap quantification.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [147492, 148101)" },
  { id: "V39", phase: "reviewedCall", label: "housing location goal", template: "What area would you like to live in?", purpose: "Reviewed call future-location specificity.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [149467, 150071)" },
  { id: "V40", phase: "reviewedCall", label: "housing cost estimate", template: "What would a home in that neighborhood cost?", purpose: "Reviewed call cost of future housing example.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [149781, 150379)" },
  { id: "V41", phase: "reviewedCall", label: "hypothetical housing budget", template: "Would that housing cost fit what you would be comfortable spending at the target income?", purpose: "Reviewed call hypothetical budget relationship, not financial advice.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [150369, 150983)" },
  { id: "V42", phase: "reviewedCall", label: "personal meaning", template: "What would achieving those things do for you personally?", purpose: "Reviewed call personal meaning after specific goals.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [150864, 151461)" },
  { id: "V43", phase: "reviewedCall", label: "gratification meaning", template: "What do you mean by gratification?", purpose: "Reviewed call probes the prospect's distinctive word; normalized from garbled ASR.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [151830, 152414)" },
  { id: "V44", phase: "reviewedCall", label: "progress metric clarification", template: "How close are you in terms of the skill set needed, not only the income target?", purpose: "Reviewed call distinction between skill progress and monetary progress; original exchange ambiguous.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [152991, 153594)" },
  { id: "V45", phase: "reviewedCall", label: "day to day consequence", template: "What would be the day-to-day ramifications of staying where you are?", purpose: "Instructor's restatement of Yosh's consequence mirror.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [154895, 155497)" },
  { id: "V46", phase: "reviewedCall", label: "financial consequence hypothesis", template: "What happens financially then?", purpose: "Reviewed call deepens the prospect's inflation/downsizing hypothesis.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [155380, 155976)" },
  { id: "V47", phase: "reviewedCall", label: "responsibility", template: "Who has to make the choice about whether to settle?", purpose: "Reviewed call commitment/responsibility.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [155583, 156190)" },
  { id: "V48", phase: "reviewedCall", label: "timing reason", template: "Why make this change now?", purpose: "Reviewed call timing commitment.", delivery: "not_audio_verified", use: "adapt", sourceRef: "A, A13, original characters [156357, 156931)" },
];

/** Records the model and the UI may draw on for live hints and angles. Only `adapt`. */
export const LIVE_QUESTIONS: readonly QuestionRecord[] = QUESTION_BANK.filter((r) => r.use === "adapt");

/** Records kept for study of the source method. Never enter a live prompt. */
export const STUDY_ONLY: readonly QuestionRecord[] = QUESTION_BANK.filter((r) => r.use === "study_only");

/** Records for the rep's own practice and reflection. Never prospect-facing. */
export const PRIVATE_TRAINING: readonly QuestionRecord[] = QUESTION_BANK.filter((r) => r.use === "private_training");

export interface BankCounts {
  total: number;
  adapt: number;
  study_only: number;
  private_training: number;
  byPhase: Record<QuestionPhase, number>;
}

function countBank(): BankCounts {
  const byPhase = {} as Record<QuestionPhase, number>;
  let adapt = 0;
  let study_only = 0;
  let private_training = 0;
  for (const r of QUESTION_BANK) {
    byPhase[r.phase] = (byPhase[r.phase] ?? 0) + 1;
    if (r.use === "adapt") adapt += 1;
    else if (r.use === "study_only") study_only += 1;
    else private_training += 1;
  }
  return { total: QUESTION_BANK.length, adapt, study_only, private_training, byPhase };
}

/** Counted from the data, not typed by hand. The source header claims 207 records. */
export const BANK_COUNTS: BankCounts = countBank();

/** The bank's own record count claim, kept beside the parsed count so a drift is visible. */
export const BANK_CLAIMED_TOTAL = 207;

/** All records for a phase, in bank order. Pass `liveOnly` to drop study_only and private_training. */
export function byPhase(phase: QuestionPhase, liveOnly = false): QuestionRecord[] {
  return QUESTION_BANK.filter((r) => r.phase === phase && (!liveOnly || r.use === "adapt"));
}

export function questionById(id: string): QuestionRecord | undefined {
  return QUESTION_BANK.find((r) => r.id === id);
}
