/**
 * Stage-level SOPs. Source: docs/spec/11_SALES_PROCESS_AND_STAGE_SOPS.md (SOS-11).
 * Versioned playbook modules per SOS-17. Language variants are illustrative, not mandated claims.
 */

export interface SopModule {
  sopId: string;
  version: string;
  stage: string;
  title: string;
  objective: string;
  entryConditions: string[];
  requiredFacts: string[];
  requiredActions: string[];
  languageVariants: string[];
  automation: string[];
  evidence: string[];
  exitConditions: string[];
  stopRules: string[];
  downstreamOwner: string;
  primaryMetricId: string;
  guardrails: string[];
  owner: string;
  effectiveDate: string;
  reviewHistory: { date: string; note: string }[];
}

export const sops: SopModule[] = [
  {
    sopId: "SOP-A",
    version: "1.0",
    stage: "intake",
    title: "Intake to accountable owner",
    objective: "Preserve the inquiry and put a responsible person on it.",
    entryConditions: ["A source inquiry has been received with a provider ID."],
    requiredFacts: ["Source ID", "Normalized contact points", "Entry path", "Source and tier snapshot", "Permission evidence"],
    requiredActions: ["Check duplicates", "Create or link opportunity", "Assign under routing policy", "Create the first task"],
    languageVariants: [],
    automation: ["Ingest", "Deduplicate", "Assign", "Notify"],
    evidence: ["Submission ID", "Opportunity ID", "Assignment ID", "Task ID"],
    exitConditions: ["Accepted responsibility", "Monitored holding queue"],
    stopRules: ["No contact without permission", "No silent reassignment to improve a score"],
    downstreamOwner: "Setter or closer by entry path",
    primaryMetricId: "M03",
    guardrails: ["Ambiguous identity goes to human review", "No eligible representative goes to holding, not to an unqualified person"],
    owner: "Sales operations",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
  {
    sopId: "SOP-B",
    version: "1.0",
    stage: "contact",
    title: "Assigned inquiry to meaningful contact",
    objective: "Respond to the actual request and establish a two-way exchange.",
    entryConditions: ["Opportunity assigned", "Permitted channel exists"],
    requiredFacts: ["The customer's request in their words", "Existing relationship", "Permitted channel and time"],
    requiredActions: ["Identify the business", "Ask whether it is a workable time", "Log provider attempts", "Distinguish no answer, voicemail, wrong contact, and meaningful interaction"],
    languageVariants: [
      "You asked about reducing the work around dealer follow-up. What part is taking the most time today?",
      "You reached out about follow-up. Is now a workable time for two minutes?",
    ],
    automation: ["Calling interface", "Event collection", "Proposed summary", "Approved retry task"],
    evidence: ["Provider call record", "Confirmed interpreted outcome"],
    exitConditions: ["Confirmed contact", "Agreed callback", "Accurately recorded outcome"],
    stopRules: ["Opt-out", "Wrong-party contact", "Repeat-contact burden exceeded"],
    downstreamOwner: "Same setter",
    primaryMetricId: "M04",
    guardrails: ["A completed provider call does not mark Contacted", "Voicemail offers the permitted next step, not fabricated notes"],
    owner: "Setter lead",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
  {
    sopId: "SOP-C",
    version: "1.0",
    stage: "booking",
    title: "Contact or booked intake to a retained appointment",
    objective: "Make the next conversation relevant, feasible, and clearly agreed.",
    entryConditions: ["Two-way contact established, or a self-booked inquiry under pre-call review"],
    requiredFacts: ["Prospect's goal", "What the appointment will resolve", "Basic fit", "Timezone and duration", "Who attends"],
    requiredActions: ["Offer real available slots", "Confirm timezone and duration", "Send preparation", "Ask what the prospect needs before the call"],
    languageVariants: [
      "What would make that conversation worth thirty minutes for you?",
      "Would you rather start with the numbers or see how it works?",
    ],
    automation: ["Slot offer", "Invitation delivery", "Confirmation tracking"],
    evidence: ["Appointment ID", "Instance ID", "Invitation delivery state"],
    exitConditions: ["Retained appointment", "Approved DQ with reason and evidence", "Nurture with permitted purpose"],
    stopRules: ["Do not force a rebook for a self-booked inquiry", "A different time is not a bad lead"],
    downstreamOwner: "Closer via handoff brief",
    primaryMetricId: "M06",
    guardrails: ["Truthful appointment purpose", "No unnecessary meetings", "No excessive reminders", "No routine overbooking"],
    owner: "Setter lead",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
  {
    sopId: "SOP-D",
    version: "1.0",
    stage: "attendance",
    title: "Retained appointment to attended conversation",
    objective: "Remove avoidable friction and be ready when the customer arrives.",
    entryConditions: ["Retained appointment instance"],
    requiredFacts: ["Link or call method", "Timezone", "Contact details", "Responsible representative"],
    requiredActions: ["Send approved reminders", "Verify presence at appointment time", "Apply grace and recovery if absent"],
    languageVariants: ["Still good for 3:00 today? Reply with a new time if not, no problem."],
    automation: ["Reminders", "Participant events", "Attendance proposals", "Recovery tasks"],
    evidence: ["Provider participant events", "Reviewed human confirmation for phone or in-person"],
    exitConditions: ["Attended", "Customer no-show with recovery task", "Rep no-show classified as service failure", "Unknown pending evidence"],
    stopRules: ["Stale reminders stop when the appointment changes or the customer replies"],
    downstreamOwner: "Closer",
    primaryMetricId: "M08",
    guardrails: ["Customer wait time", "Contact burden", "A calendar event alone is never attendance"],
    owner: "Sales operations",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
  {
    sopId: "SOP-E",
    version: "1.0",
    stage: "fit",
    title: "Conversation to fit assessment",
    objective: "Understand whether the offer addresses the problem and what remains unknown.",
    entryConditions: ["Attended conversation"],
    requiredFacts: ["Current process", "Desired outcome", "Business constraints", "Decision participants", "Implementation readiness", "Budget and timing where appropriate"],
    requiredActions: ["Separate stated from verified", "Apply the offer's objective criteria", "Record rep-perceived fit separately"],
    languageVariants: ["Who would use this day to day, and who needs to agree before you change the process?"],
    automation: ["Evidence extraction proposal", "Missing-question prompt"],
    evidence: ["Assessment record with policy version"],
    exitConditions: ["Fit likely with unknowns listed", "Clarify", "Unsuitable, recorded accurately"],
    stopRules: ["Do not convert an unknown answer into a hard rejection"],
    downstreamOwner: "Closer for recommendation",
    primaryMetricId: "M09",
    guardrails: ["No unsuitable sales", "No post-hoc DQ", "A high perceived-qualified rate is not automatically good"],
    owner: "Closer lead",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
  {
    sopId: "SOP-F",
    version: "1.0",
    stage: "decision",
    title: "Fit to recommendation and decision",
    objective: "Offer a relevant, accurate solution and help the customer evaluate it.",
    entryConditions: ["Fit assessed"],
    requiredFacts: ["Agreed outcome", "Approved scope and version", "Implementation responsibilities", "Limitations", "Price and options"],
    requiredActions: ["Restate the problem", "Present only approved scope", "Resolve actual uncertainty", "Ask for the next voluntary decision"],
    languageVariants: [
      "Based on what you described, this option addresses X. It does not handle Y. Would you like to review the implementation steps or the economics first?",
    ],
    automation: ["Offer facts panel", "Exception routing to approver"],
    evidence: ["Proposal record", "Decision outcome"],
    exitConditions: ["Verbal yes with follow-up task", "No-sale recorded with reason", "Conditional next step"],
    stopRules: ["No unapproved guarantees", "No pressure because the month is ending"],
    downstreamOwner: "Closer for contract",
    primaryMetricId: "M11",
    guardrails: ["Discount authority enforced outside the model", "Unsuitable offer is not an objection to defeat"],
    owner: "Closer lead",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
  {
    sopId: "SOP-G",
    version: "1.0",
    stage: "collection",
    title: "Decision to contract and collection",
    objective: "Document agreement accurately and reconcile actual money.",
    entryConditions: ["Voluntary decision to proceed"],
    requiredFacts: ["Correct offer and contract version", "Authorized signer", "Payment destination is the business account"],
    requiredActions: ["Create contract", "Obtain signatures", "Issue payment through the business provider", "Track partial or delayed payment"],
    languageVariants: [],
    automation: ["Contract generation", "Payment link", "Ledger reconciliation"],
    evidence: ["Contract ID", "Ledger entries with provider references"],
    exitConditions: ["Collected", "Partially collected with follow-up", "Failed payment with support task"],
    stopRules: ["Verbal yes, signature, authorization, collection, and payout stay distinct"],
    downstreamOwner: "Delivery",
    primaryMetricId: "M16",
    guardrails: ["No duplicate charges", "No unauthorized terms", "No card data in the app"],
    owner: "Finance",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
  {
    sopId: "SOP-H",
    version: "1.0",
    stage: "delivery",
    title: "Collected sale to delivery and retention",
    objective: "Fulfill what was sold and preserve the relationship.",
    entryConditions: ["Contract signed and payment state known"],
    requiredFacts: ["Scope and version", "Promises", "Dependencies", "Paid and outstanding", "Deadline", "Acceptance criteria"],
    requiredActions: ["Create delivery brief", "Delivery accepts responsibility", "Flag unfulfillable promises"],
    languageVariants: [],
    automation: ["Delivery brief generation", "Handoff acceptance tracking"],
    evidence: ["Handoff acceptance record"],
    exitConditions: ["Delivery accepted", "Gap flagged for resolution"],
    stopRules: ["Selling faster than the business can deliver"],
    downstreamOwner: "Delivery owner",
    primaryMetricId: "M18",
    guardrails: ["A payment does not prove delivery capacity"],
    owner: "Delivery lead",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
  {
    sopId: "SOP-I",
    version: "1.0",
    stage: "nurture",
    title: "Lost, DQ, nurture, and reactivation",
    objective: "Record the actual reason and keep the relationship honest.",
    entryConditions: ["Opportunity leaves the active path"],
    requiredFacts: ["Reason code", "Evidence", "Permitted nurture purpose and channel"],
    requiredActions: ["Differentiate fit, timing, no decision, budget under policy, competitor, unreachable, opt-out", "Keep history", "Create a new opportunity only when the buying-cycle policy warrants it"],
    languageVariants: [],
    automation: ["Nurture sequence with stop rules"],
    evidence: ["Reason record", "Reactivation link to prior opportunity"],
    exitConditions: ["Nurture", "Closed with reason", "Reactivated as new opportunity"],
    stopRules: ["No amount of gamification overrides a stop request"],
    downstreamOwner: "Setter for nurture",
    primaryMetricId: "M07",
    guardrails: ["Loss and DQ categories never hide attendance or improve denominators"],
    owner: "Sales operations",
    effectiveDate: "2026-09-18",
    reviewHistory: [{ date: "2026-09-18", note: "Initial version from SOS-11." }],
  },
];
